GET http://localhost:4000/api/recipes

###

GET http://localhost:4000/api/recipes/661d865776681f8db2f44e5a

###

POST http://localhost:4000/api/recipes/new
Content-Type: application/json

{ 
  "name": "burgers",
  "image": "https://images.pexels.com/photos/70497/pexels-photo-70497.jpeg?auto=compress&cs=tinysrgb&w=600",
  "rating": 5,
  "ingredients": "blah blah blah",
  "directions": "do it yourself"
}

###

DELETE http://localhost:4000/api/recipes/delete/661eed1812d32ac5b2f2998c

###

PATCH http://localhost:4000/api/recipes/update/661eed1512d32ac5b2f29982
Content-Type: application/json

{
  "text": "Updated Recipe"
}