GET http://localhost:4000/api/recipes

###

GET http://localhost:4000/api/recipes/661d865776681f8db2f44e5a

###

POST http://localhost:4000/api/recipes/new
Content-Type: application/json

{
  "text": "New Recipe"
}

###

DELETE http://localhost:4000/api/recipes/delete/661e405807ef8bc4051c59e6

###

PATCH http://localhost:4000/api/recipes/update/661e428a6a7ed9a9cc242022
Content-Type: application/json

{
  "text": "Updated Recipe"
}